### PR TITLE
Support For Private Key Login & Misc.

### PR DESCRIPTION
**Pull request by adamzr**
- Support OAuth based SF logins
- Dependency upgrades (needed for OAuth and tests)
- Fix README code

### CODE REVIEW

**Comment by adamzr** [comment]
Fixes #19 

Thanks for creating this project! Very useful.

I login using a private key of a connected app. This PR updates to mock that Salesforce call as well. I had to update the Salesforce dependency version and the pytest version to get it to work.

I also fixed a minor error in the example code in the README.

Thank you!

**Comment by adamzr** [comment]
@brno32 @Safintim Hi, can you please review this PR?

**Comment by brno32** [comment]
Thanks for this contribution! Would you be able to add a unit test to cover the OAuth stuff?

Also, the tests failed with this weird import error

https://github.com/Kicksaw-Consulting/simple-mockforce/actions/runs/3003569516/jobs/4896568736

I don't think this has anything to do with your change, though. We'll have to investigate!

**Comment by adamzr** [comment]
@brno32 I added a test that just copies one of your regular tests, but uses OAuth credentials. See https://github.com/Kicksaw-Consulting/simple-mockforce/pull/21/files#diff-63ff39fb53d411813d938ec712d5716caee4352d5d5d1e02b5955fad01486550R33

**Comment by adamzr** [comment]
@brno32 I was using a newer version of Poetry locally and I had to update dependencies. Maybe that broke it? I just pushed another commit to upgrade Poetry in the GitHub Action workflow. If you run it again, we can see if that fixes it.

**Comment by men6288** [comment]
This MR would be super helpful to have, we use a oauth app as well. Let me know if there's any way I can test as well

**Comment by adamzr** [comment]
@brno32 Can you re-run the workflows?

**Review by georgebv — APPROVED** [review]

**Comment by georgebv** [comment]
Thank you @adamzr for your contribution and patience. I have merged your changes. There is an issue with API version being hard coded in older tests which we will be fixing before publishing a new release with your changes incorporated. Cannot give an ETA on that though.

**Comment by brno32** [comment]
Fixed the test here https://github.com/Kicksaw-Consulting/simple-mockforce/pull/22

**Comment by brno32** [comment]
https://pypi.org/project/simple-mockforce/ `0.5.0` is on pypi. @adamzr thanks a lot for the contribution!

**Pull request merged**
